export const introSectionStyles = {
  container: {
    width: "100%",
    height: "100vh",
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  image_container: {
    position: "absolute",
    overflow: "hidden",
    zIndex: 1,
    top: 0,
    left: 0,
  },
  relative_container: {
    position: "relative",
    width: "100%",
    height: "100%",
    overflow: "hidden",
  },
  main_text_container: {
    position: "absolute",
    zIndex: 1,
    fontSize: "9vw",
    fontFamily: "Tiro Bangla, serif",
    fontWeight: 300,
  },
  container2: {
    position: "relative",
    width: "100%",
    height: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  container2_header: {
    fontSize: "2.4vw",
    fontWeight: 400,
    width: "75%",
    textAlign: "left",
  },
  container2_inner: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "1vw",
  },
  section_container2: {
    width: "22%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    margin: "0 2vw",
  },
  section_innercontainer2: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    borderTop: "1px solid rgb(158, 158, 158)",
  },
  section_container2_number: {
    textAlign: "left",
    width: "100%",
    fontSize: "1vw",
    color: "rgb(158, 158, 158)",
    marginBottom: "2vw",
  },
  section_container2_title: {
    position: "relative",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "2vw",
    fontFamily: "Aboreto ,cursive",
  },
  icon: {
    position: "absolute",
    right: 0,
    width: "3vw",
    height: "3vw",
  },
  section_container2_content: {
    fontSize: "1.2vw",
    fontWeight: 300,
  },
  container3: {
    position: "relative",
    width: "100%",
    height: "150vh",
    zIndex: -1,
  },
};

export const firstSectionStyles = {
  container: {
    width: "100%",
    height: "100vh",
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  inner_container: {
    width: "80%",
  },
  title: {
    fontSize: "4vw",
    width: "40%",
  },
  image: {
    width: "25vw",
    height: "35vw",
    position: "relative",
    overflow: "hidden",
  },
  image_inner: {
    position: "relative",
    width: "calc(100% + 200px)",
    height: "calc(100% + 300px)",
    overflow: "hidden",
    top: -200,
  },
  container1: {
    width: "100%",
    height: "150vh",
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  inner_container1: {
    width: "80%",
    height: "95%",
    position: "relative",
  },
  container1_title: {
    fontSize: "4vw",
    width: " 35%",
    position: "absolute",
    overflow: "hidden",
    top: 0,
  },
  container1_slogan: {
    position: "absolute",
    width: "25%",
    top: "20%",
    fontWeight: 800,
  },
  container1_title1: {
    position: "absolute",
    right: "19vw",
    top: "4vw",
    fontSize: "4vw",
    color: "#050505",
    overflow: "hidden",
  },
  image1: {
    width: "45vw",
    height: "30vw",
    position: "absolute",
    // overflow: "hidden",
    right: 0,
    top: "25vw",
  },
  image_inner1: {
    position: "relative",
    width: "calc(100% + 200px)",
    height: "calc(100% + 300px)",
    // overflow: "hidden",
    top: -200,
  },
  container1_para: {
    position: "absolute",
    width: "45vw",
    fontSize: "1.1vw",
    fontWeight: 300,
    right: 0,
    textAlign: "left",
    top: "14vw",
  },
  container1_link: {
    position: "absolute",
    width: "8vw",
    height: "8vw",
    borderRadius: "50%",
    top: "25vw",
    left: "22vw",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#050505",
    color: "#fff",
    // fontWeight: 600,
    cursor: "pointer",
    overflow: "hidden",
  },
  arrow_icon: {
    width: "2vw",
    height: "2vw",
    position: "absolute",
    zIndex: 2,
  },

  container1_link_text: {
    position: "absolute",
    zIndex: 2,
    color: "#050505",
    fontWeight: 600,
  },

  icon_background: {
    width: "8vw",
    height: "8vw",
    borderRadius: "50%",
    position: "absolute",
    zIndex: 1,
    backgroundColor: "#fff",
  },
  container2: {
    width: "100%",
    height: "100vh",
    position: "relative",
    display: "flex",
    justifyContent: "center",
  },
  inner_container2: {
    width: "80%",
    height: "100%",
    position: "relative",
  },
  container2_title: {
    fontSize: "4vw",
    position: "absolute",
    display: "flex",
    flexDirection: "column",
    right: "27vw",
    top: "-15vw",
    color: "#050505",
  },
  image2: {
    width: "25vw",
    height: "35vw",
    position: "absolute",
    top: "5vw",
  },
  container2_para: {
    position: "absolute",
    width: "30%",
    top: "3.5vw",
    left: "30vw",
    fontSize: "1.1vw",
    fontWeight: 300,
  },
  container2_slogan: {
    position: "absolute",
    right: 0,
    width: "25%",
    fontWeight: 800,
    textAlign: "right",
    fontSize: "1.2vw",
    top: "15vw",
  },
};
